Add is location walkable
nwn-dotnet/NWN.Managed pull request #127
Opened 2021-02-16 17:40 UTC by urothis

Not sure if this is the ideal solution.

2021-02-16 18:03 UTC, milliorn commented
Look OK.

2021-02-16 19:05 UTC, Jorteck requested changes
The location parameter isn't needed, you can use "this" instead and make it a property.

2021-02-22 10:56 UTC, Jorteck requested changes

2021-02-22 10:56 UTC, Jorteck commented on src/main/NWN/API/Location/Location.Managed.cs
> +      => NWScript.Get2DAString("surfacemat", "Walk", this.SurfaceMaterial).ParseIntBool();
This can be changed to a property.

2021-02-23 17:25 UTC, Jorteck approved these changes

2021-02-23 17:25 UTC, merged